In [1]:
%load_ext autoreload
%autoreload 2
from src.data import make_data

ImportError: cannot import name 'make_data' from 'src.data' (/Users/robin/Documents/nf-ds/capstone/src/data/__init__.py)

In [2]:
import urllib.request, json 
import pandas as pd
from dotenv import find_dotenv, load_dotenv
# 
import pymarketstore as pymkts

In [3]:
#env_vars = find_env()
#load_dotenv(env_vars)
load_dotenv(find_dotenv())

True

In [23]:
ur = 'https://cloud.iexapis.com/beta/ref-data/exchange/ETR/symbols?token=sk_6bf534a90f9444cdaf91c67a27562f3b'
with urllib.request.urlopen(ur) as url:
    data = json.loads(url.read().decode())
    #print(data)

In [6]:
type(data)

list

In [49]:
data[148]

{'symbol': 'ADS-GY',
 'exchange': 'ETR',
 'name': 'adidas AG',
 'date': '2019-12-03',
 'type': 'cs',
 'iexId': 'IEX_5144595952522D52',
 'region': 'DE',
 'currency': 'EUR',
 'isEnabled': True}

In [52]:
[i for i in range(len(data)) if data[i]['name'].find('volks') == 0]

[]

In [39]:
list_names = [x['name'] for x in data]
list_symbols = [x['symbol'] for x in data]

In [24]:
data2 = data

In [25]:
dic = {data2[i]['symbol']: data2[i] for i in range(len(data2))}

In [34]:
js = json.dumps(dic)

In [56]:
df = pd.DataFrame.from_dict(dic)

In [57]:
df.head()

,00XJ-GY,00XK-GY,00XM-GY,00XN-GY,00XP-GY,00XR-GY,00XS-GY,0GZA-GY,0GZB-GY,0GZC-GY,...,YOC-GY,YSN-GY,ZAL-GY,ZEF-GY,ZEG-GY,ZFIN-GY,ZIL2-GY,ZO1-GY,ZSOL-GY,ZTWN-GY
currency,EUR,EUR,EUR,EUR,EUR,EUR,EUR,EUR,EUR,EUR,...,EUR,EUR,EUR,EUR,EUR,EUR,EUR,EUR,EUR,EUR
date,2019-12-03,2019-12-03,2019-12-03,2019-12-03,2019-12-03,2019-12-03,2019-12-03,2019-12-03,2019-12-03,2019-12-03,...,2019-12-03,2019-12-03,2019-12-03,2019-12-03,2019-12-03,2019-12-03,2019-12-03,2019-12-03,2019-12-03,2019-12-03
exchange,ETR,ETR,ETR,ETR,ETR,ETR,ETR,ETR,ETR,ETR,...,ETR,ETR,ETR,ETR,ETR,ETR,ETR,ETR,ETR,ETR
iexId,IEX_465250385A522D52,IEX_4742564732382D52,IEX_4D31355251442D52,IEX_4D4D425853582D52,IEX_5339503747312D52,IEX_4E53503759592D52,IEX_5043564631472D52,IEX_5454385846482D52,IEX_534D594C38472D52,IEX_54373352425A2D52,...,IEX_4A4B484E304A2D52,IEX_4A5958544E302D52,IEX_504D364B50322D52,IEX_424D473242332D52,IEX_42563446504C2D52,IEX_4B504C5647532D52,IEX_4A564A3737582D52,IEX_524C444732572D52,IEX_48385052514B2D52,IEX_4E42473552302D52
isEnabled,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True

In [73]:
df2['type'].unique()

array(['et', 'struct', 'cs', 'oef', 'wt', 'ad', 'temp', 'cef', 'ps', '',
       'gd'], dtype=object)

In [74]:
df3 = df2[df2['type'] == 'cs']

In [76]:
df3.shape

(773, 9)

In [77]:
df3

,currency,date,exchange,iexId,isEnabled,name,region,symbol,type
0UB-GY,EUR,2019-12-03,ETR,IEX_44514B4838512D52,True,UBS Group AG,DE,0UB-GY,cs
1COV-GY,EUR,2019-12-03,ETR,IEX_47564A32584E2D52,True,Covestro AG,DE,1COV-GY,cs
1FC-GY,EUR,2019-12-03,ETR,IEX_584739464B4B2D52,True,FACC AG,DE,1FC-GY,cs
1NBA-GY,EUR,2019-12-03,ETR,IEX_4E3244484A502D52,True,Anheuser-Busch InBev SA/NV,DE,1NBA-GY,cs
1P2N-GY,EUR,2019-12-03,ETR,IEX_575A4A3559572D52,True,Prophecy Development Corp.,DE,1P2N-GY,cs
1SI-GY,EUR,2019-12-03,ETR,IEX_513254304D512D52,True,Snap Inc. Class A,DE,1SI-GY,cs
1T2-GY,EUR,2019-12-03,ETR,IEX_4448445131422D52,True,VST Building Technologies AG,DE,1T2-GY,cs
2FE-GY,EUR,2019-12-03,ETR,IEX_4354464A434A2D52,True,Ferrari NV,DE,2FE-GY,cs
2FI-GY,EUR,2019-12-03,ETR,IEX_54394E424C322D52,True,Fiat Chrysler Automobiles N.V.,DE,2FI-GY,cs
2GB-GY,EUR,2019-12-03,ETR,IEX_4837434C42312D52,True,2G Energy AG,DE,2GB-GY,cs
2HRA-GY,EUR,2019-12-03,ETR,IEX_52334A4E33392D52,True,H&R GmbH & Co. KGaA,DE,2HRA-GY,cs
2KD-GY,EUR,2019-12-03,ETR,IEX_5831334A35392D52,True,Kinder Morgan Inc Class P,DE,2KD-GY,cs
2M6-GY,EUR,2019-12-03,ETR,IEX_434B5A364B542D52,True,Medtronic Plc,DE,2M6-GY,cs
2O4-GY,BGN,2019-12-03,ETR,IEX_42524C5846442D52,True,ONI Holdings AD,DE,2O4-GY,cs
2PP-GY,EUR,2019-12-03,ETR,IEX_52374B3736512D52,True,PayPal Holdings Inc,DE,2PP-GY,cs
2QU-GY,EUR,2019-12-03,ETR,IEX_4C37423750542D52,True,onoff AG,DE,2QU-GY,cs
3HX-GY,EUR,2019-12-03,ETR,IEX_4C56543431342D52,True,Onco Petroleum Inc,DE,3HX-GY,cs
3JG-GY,BGN,2019-12-03,ETR,IEX_4C42534C444A2D52,True,Sevko AD,DE,3JG-GY,cs
3RB-GY,EUR,2019-12-03,ETR,IEX_4E355439395A2D52,True,Reckitt Benckiser Group plc,DE,3RB-GY,cs
3V64-GY,EUR,2019-12-03,ETR,IEX_464E513135392D52,True,Visa Inc. Class A,DE,3V64-GY,cs
45DA-GY,EUR,2019-12-03,ETR,IEX_50385A4A4A312D52,True,Ensurapet Inc.,DE,45DA-GY,cs
4DS-GY,EUR,2019-12-03,ETR,IEX_4B43383152562D52,True,Daldrup & Soehne AG,DE,4DS-GY,cs
4HV-GY,EUR,2019-12-03,ETR,IEX_5135355354462D52,True,Maple Leaf Green World Inc.,DE,4HV-GY,cs
4I1-GY,EUR,2019-12-03,ETR,IEX_4448374250352D52,True,Philip Morris International Inc.,DE,4I1-GY,cs
4IM-GY,BGN,2019-12-03,ETR,IEX_4B58344336422D52,True,IMMI AD,DE,4IM-GY,cs
4JY1-GY,EUR,2019-12-03,ETR,IEX_4D36345754352D52,True,PT Bank BTPN Tbk,DE,4JY1-GY,cs
4OI-GY,EUR,2019-12-03,ETR,IEX_464B434A4E312D52,True,Stratos Renewables Corporation,DE,4OI-GY,cs
5AB-GY,EUR,2019-12-03,ETR,IEX_465644464C562D52,True,Asian Bamboo AG,DE,5AB-GY,cs
5R9-GY,BGN,2019-12-03,ETR,IEX_56314A4D58382D52,True,Ruen Holding AD,DE,5R9-GY,cs
690D-GY,EUR,2019-12-03,ETR,IEX_51563036384E2D52,True,Haier Smart Home Co. Ltd. Class D,DE,690D-GY,cs
...,...,...,...,...,...,...,...,...,...
WDI-GY,EUR,2019-12-03,ETR,IEX_5834325158512D52,True,Wirecard AG,DE,WDI-GY,cs
WDLK-GY,EUR,2019-12-03,ETR,IEX_473947464A442D52,True,windeln.de SE,DE,WDLK-GY,cs
WEG1-GY,EUR,2019-12-03,ETR,IEX_46345056514A2D52,True,Westgrund Aktiengesellschaft,DE,WEG1-GY,cs
WELA-GY,EUR,2019-12-03,ETR,IEX_4D36315353342D52,True,A.C.N. 059 457 279 Limited,DE,WELA-GY,cs
WEW-GY,EUR,2019-12-03,ETR,IEX_4A51445351562D52,True,Westwing Group AG,DE,WEW-GY,cs
WGF1-GY,EUR,2019-12-03,ETR,IEX_44374C4E38312D52,True,Williams Grand Prix Holdings PLC,DE,WGF1-GY,cs
WIG1-GY,EUR,2019-12-03,ETR,IEX_504B5643505A2D52,True,SPORTTOTAL AG,DE,WIG1-GY,cs
WIN-GY,EUR,2019-12-03,ETR,IEX_4230323636322D52,True,Diebold Nixdorf AG,DE,WIN-GY,cs
WL6-GY,EUR,2019-12-03,ETR,IEX_42444D4448422D52,True,Heidelberg Pharma AG,DE,WL6-GY,cs
WMT-GY,EUR,2019-12-03,ETR,IEX_424D394847502D52,True,Walmart Inc.,DE,WMT-GY,cs
WSO1-GY,EUR,2019-12-03,ETR,IEX_52434E4B4B512D52,True,wallstreet:online AG,DE,WSO1-GY,cs
WSU-GY,EUR,2019-12-03,ETR,IEX_52444D37344B2D52,True,WashTec AG,DE,WSU-GY,cs
WSV2-GY,EUR,2019-12-03,ETR,IEX_4C44373730582D52,True,Vienna Insurance Group AG Wiener Versicherung ...,DE,WSV2-GY,cs
WUG-GY,EUR,2019-12-03,ETR,IEX_5357313442562D52,True,Westag & Getalit AG,DE,WUG-GY,cs
WUW-GY,EUR,2019-12-03,ETR,IEX_463944314D532D52,True,Wuestenrot & Wuerttembergische AG,DE,WUW-GY,cs
XB6-GY,EUR,2019-12-03,ETR,IEX_5053514630582D52,True,Xebec Adsorption Inc.,DE,XB6-GY,cs
XCA-GY,EUR,2019-12-03,ETR,IEX_425052324D4D2D52,True,Credit Agricole SA,DE,XCA-GY,cs
XONA-GY,EUR,2019-12-03,ETR,IEX_503851354C362D52,True,Exxon Mobil Corporation,DE,XONA-GY,cs
Y7R-GY,EUR,2019-12-03,ETR,IEX_4B4E534B43352D52,True,YD Ynvisible S.A.,DE,Y7R-GY,cs
YCP-GY,EUR,2019-12-03,ETR,IEX_50364C4B464D2D52,True,ConocoPhillips,DE,YCP-GY,cs
YOC-GY,EUR,2019-12-03,ETR,IEX_4A4B484E304A2D52,True,YOC AG,DE,YOC-GY,cs
YSN-GY,EUR,2019-12-03,ETR,IEX_4A5958544E302D52,True,secunet Security Networks AG,DE,YSN-GY,cs
ZAL-GY,EUR,2019-12-03,ETR,IEX_504D364B50322D52,True,Zalando SE,DE,ZAL-GY,cs
ZEF-GY,EUR,2019-12-03,ETR,IEX_424D473242332D52,True,ZhongDe Waste Technology AG,DE,ZEF-GY,cs
ZEG-GY,EUR,2019-12-03,ETR,IEX_42563446504C2D52,True,AstraZeneca PLC,DE,ZEG-GY,cs
ZFIN-GY,EUR,2019-12-03,ETR,IEX_4B504C5647532D52,True,Zurich Insurance Group Ltd,DE,ZFIN-GY,cs
ZIL2-GY,EUR,2019-12-03,ETR,IEX_4A564A3737582D52,True,ElringKlinger AG,DE,ZIL2-GY,cs
ZO1-GY,EUR,2019-12-03,ETR,IEX_524C444732572D52,True,zooplus AG,DE,ZO1-GY,cs
ZSOL-GY,EUR,2019-12-03,ETR,IEX_48385052514B2D52,True,Solutiance AG,DE,ZSOL-GY,cs
ZTWN-GY,EUR,2019-12-03,ETR,IEX_4E42473552302D52,True,Fortune Graphite Inc.,DE,ZTWN-GY,cs

In [72]:
df2[df2['name'].str.contains('adidas')]

,currency,date,exchange,iexId,isEnabled,name,region,symbol,type
ADS-GY,EUR,2019-12-03,ETR,IEX_5144595952522D52,True,adidas AG,DE,ADS-GY,cs

In [78]:
!pwd

/Users/robin/Nextcloud2/Coding/atomm

In [93]:
cd /Users/robin/Documents/projects/python/test/

/Users/robin/Documents/projects/python/test

In [94]:
pwd

'/Users/robin/Documents/projects/python/test'

In [83]:
import pickle

In [101]:
pickle.dump(df.T, open('iex_symbols_xetra.pkl', 'wb'))

In [124]:
pkl_df = pickle.load(open('iex_symbols_xetra.pkl', 'rb'))

TypeError: object of type '_io.BufferedReader' has no len()

In [125]:
pkl_df[(pkl_df['name'].str.contains('Deutsche')) & (pkl_df['type'] == 'cs')]

,currency,date,exchange,iexId,isEnabled,name,region,symbol,type
DB1-GY,EUR,2019-12-03,ETR,IEX_5254365736352D52,True,Deutsche Boerse AG,DE,DB1-GY,cs
DBAN-GY,EUR,2019-12-03,ETR,IEX_4C47424B4E372D52,True,Deutsche Beteiligungs AG,DE,DBAN-GY,cs
DBK-GY,EUR,2019-12-03,ETR,IEX_5336514C50312D52,True,Deutsche Bank AG,DE,DBK-GY,cs
DEF-GY,EUR,2019-12-03,ETR,IEX_4A4D424458462D52,True,DEFAMA Deutsche Fachmarkt AG,DE,DEF-GY,cs
DEQ-GY,EUR,2019-12-03,ETR,IEX_543637584A342D52,True,Deutsche EuroShop AG,DE,DEQ-GY,cs
DFTK-GY,EUR,2019-12-03,ETR,IEX_514833334B472D52,True,DF Deutsche Forfait AG,DE,DFTK-GY,cs
DFV-GY,EUR,2019-12-03,ETR,IEX_5347304B344D2D52,True,DFV Deutsche Familienversicherung AG,DE,DFV-GY,cs
DGR-GY,EUR,2019-12-03,ETR,IEX_564D4A4E4E462D52,True,Deutsche Grundstucksauktionen AG,DE,DGR-GY,cs
DKG-GY,EUR,2019-12-03,ETR,IEX_5432503554512D52,True,Deutsche Konsum REIT-AG,DE,DKG-GY,cs
DMRE-GY,EUR,2019-12-03,ETR,IEX_4C39565632312D52,True,DEMIRE Deutsche Mittelstand Real Estate AG,DE,DMRE-GY,cs
DPW-GY,EUR,2019-12-03,ETR,IEX_56335232585A2D52,True,Deutsche Post AG,DE,DPW-GY,cs
DR0-GY,EUR,2019-12-03,ETR,IEX_4A48374D4C592D52,True,Deutsche Rohstoff AG,DE,DR0-GY,cs
DTE-GY,EUR,2019-12-03,ETR,IEX_444D584B4A422D52,True,Deutsche Telekom AG,DE,DTE-GY,cs
DWNI-GY,EUR,2019-12-03,ETR,IEX_4D42535231312D52,True,Deutsche Wohnen SE,DE,DWNI-GY,cs
EFF-GY,EUR,2019-12-03,ETR,IEX_4D5236564A472D52,True,Deutsche Effecten- und Wechsel-Beteiligungsges...,DE,EFF-GY,cs
HEMP-GY,EUR,2019-12-03,ETR,IEX_4E374C5757502D52,True,Deutsche Cannabis AG,DE,HEMP-GY,cs
JB7-GY,EUR,2019-12-03,ETR,IEX_4A424B4332342D52,True,Deutsche Industrie REIT-AG,DE,JB7-GY,cs
LHA-GY,EUR,2019-12-03,ETR,IEX_4A30434C35342D52,True,Deutsche Lufthansa AG,DE,LHA-GY,cs
LOUD-GY,EUR,2019-12-03,ETR,IEX_4A50563244502D52,True,DEAG Deutsche Entertainment Aktiengesellschaft,DE,LOUD-GY,cs
PBB-GY,EUR,2019-12-03,ETR,IEX_4B30505259322D52,True,Deutsche Pfandbriefbank AG,DE,PBB-GY,cs

# Storing historical US stock data to MarketStore DB

In [78]:
import pymarketstore as pymkts
import numpy as np
import pandas as pd
import datetime as dt

In [7]:
data = np.array([(pd.Timestamp('2017-01-01 00:00').value / 10**9, 10.0)], dtype=[('Epoch', 'i8'), ('Open', 'f4')])

In [8]:
data

array([(1483228800, 10.)], dtype=[('Epoch', '<i8'), ('Ask', '<f4')])

In [16]:
df = pd.read_csv('/Users/robin/Documents/nf-ds/capstone_nf/data/raw/Data/Stocks/aapl.us.txt', parse_dates=True, index_col='Date')

               Open     High      Low    Close    Volume  OpenInt
Date
1984-09-07  0.42388  0.42902  0.41874  0.42388  23220030        0
1984-09-10  0.42388  0.42516  0.41366  0.42134  18022532        0
1984-09-11  0.42516  0.43668  0.42516  0.42902  42498199        0
1984-09-12  0.42902  0.43157  0.41618  0.41618  37125801        0
1984-09-13  0.43927  0.44052  0.43927  0.43927  57822062        0

In [18]:
df.tail()

              Open    High     Low   Close    Volume  OpenInt
Date
2017-11-06  171.75  174.36  171.10  173.63  34901241        0
2017-11-07  173.29  174.51  173.29  174.18  24424877        0
2017-11-08  174.03  175.61  173.71  175.61  24451166        0
2017-11-09  174.48  175.46  172.52  175.25  29533086        0
2017-11-10  175.11  175.38  174.27  174.67  25130494        0

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 8364 entries, 1984-09-07 to 2017-11-10
Data columns (total 6 columns):
Open       8364 non-null float64
High       8364 non-null float64
Low        8364 non-null float64
Close      8364 non-null float64
Volume     8364 non-null int64
OpenInt    8364 non-null int64
dtypes: float64(4), int64(2)
memory usage: 457.4 KB

In [21]:
df.index[0]

Timestamp('1984-09-07 00:00:00')

In [41]:
df

               Open     High      Low    Close     Volume  OpenInt
Date
1984-09-07  0.42388  0.42902  0.41874  0.42388   23220030        0
1984-09-10  0.42388  0.42516  0.41366  0.42134   18022532        0
1984-09-11  0.42516  0.43668  0.42516  0.42902   42498199        0
1984-09-12  0.42902  0.43157  0.41618  0.41618   37125801        0
1984-09-13  0.43927  0.44052  0.43927  0.43927   57822062        0
...             ...      ...      ...      ...        ...      ...
1999-12-30  3.27190  3.33360  3.19000  3.21170   57768951        0
1999-12-31  3.23090  3.29380  3.18620  3.29120   45684169        0
2000-01-03  3.35770  3.60110  3.25540  3.58330  149424648        0
2000-01-04  3.46520  3.54220  3.23990  3.28100  142893423        0
2000-01-05  3.32200  3.53970  3.29760  3.32950  217060697        0

[3874 rows x 6 columns]

In [ ]:
data = np.array([(pd.Timestamp('20-01-01 00:00').value / 10**9, 10.0)], dtype=[('Epoch', 'i8'), ('Ask', 'f4')])

In [50]:
da = df.loc[:pd.Timestamp(year=2014, month=12, day=9)].copy()

In [51]:
da.tail()

              Open    High     Low   Close    Volume  OpenInt
Date
2014-12-03  109.57  110.14  108.98  109.73  45449566        0
2014-12-04  109.58  110.95  109.14  109.34  44522535        0
2014-12-05  109.79  109.88  108.52  108.87  40469204        0
2014-12-08  108.00  108.52  105.67  106.39  60872177        0
2014-12-09  104.32  108.20  103.52  108.02  63577767        0

In [47]:
data = np.array([(da.index[i].value / 10**9, da['Open'][i], da['High'][i],da['Low'][i], da['Close'][i], da['Volume'][i]) for i in range(len(da))],
                 dtype=[('Epoch', 'i8'), ('Open', 'f4'), ('High', 'f4'), ('Low', 'f4'), ('Close', 'f4'), ('Volume', 'i8')])

In [48]:
data

array([( 463363200,   0.42388,   0.42902,   0.41874,   0.42388, 23220030),
       ( 463622400,   0.42388,   0.42516,   0.41366,   0.42134, 18022532),
       ( 463708800,   0.42516,   0.43668,   0.42516,   0.42902, 42498199),
       ...,
       (1417392000, 112.47   , 112.89   , 105.32   , 108.94   , 88523014),
       (1417478400, 107.44   , 109.57   , 106.74   , 108.51   , 62668871),
       (1417564800, 109.57   , 110.14   , 108.98   , 109.73   , 45449566)],
      dtype=[('Epoch', '<i8'), ('Open', '<f4'), ('High', '<f4'), ('Low', '<f4'), ('Close', '<f4'), ('Volume', '<i8')])

In [42]:
# Importing the atomm project specific libraries
from atomm.Indicators import MomentumIndicators
from atomm.DataManager.main import MSDataManager

In [43]:
dm = MSDataManager()

In [45]:
dm.ReturnData('AAPL', limit=None)

,Open,High,Low,Close,Volume
Epoch,,,,,
2014-12-03 00:00:00+00:00,115.750000,116.349998,115.110001,115.930000,43063440
2014-12-04 00:00:00+00:00,115.769997,117.199997,115.290001,115.489998,42155776
2014-12-05 00:00:00+00:00,115.989998,116.080002,114.639999,115.000000,38318895
2014-12-08 00:00:00+00:00,114.099998,114.650002,111.620003,112.400002,57664850
2014-12-09 00:00:00+00:00,110.190002,114.300003,109.349998,114.120003,60208036
...,...,...,...,...,...
2019-11-27 00:00:00+00:00,265.579987,267.980011,265.309998,267.839996,16386122
2019-11-29 00:00:00+00:00,266.600006,268.000000,265.899994,267.250000,11654363
2019-12-02 00:00:00+00:00,267.269989,268.250000,263.450012,264.160004,23693550
2019-12-03 00:00:00+00:00,258.309998,259.529999,256.290009,259.450012,29377268
2019-12-04 00:00:00+00:00,261.070007,263.309998,260.679993,261.739990,16810388

In [53]:
df2 = pd.read_csv('/Users/robin/Documents/nf-ds/capstone_nf/data/raw/historical_stock_prices.csv')

In [56]:
aapl = df2[df2['ticker'] == 'AAPL'].copy()

In [61]:
aapl.set_index('date', inplace=True,)

In [65]:
aapl.index = [pd.Timestamp(x) for x in aapl.index]

In [70]:
aapl.index

DatetimeIndex(['1980-12-12', '1980-12-15', '1980-12-16', '1980-12-17',
               '1980-12-18', '1980-12-19', '1980-12-22', '1980-12-23',
               '1980-12-24', '1980-12-26',
               ...
               '2018-08-13', '2018-08-14', '2018-08-15', '2018-08-16',
               '2018-08-17', '2018-08-20', '2018-08-21', '2018-08-22',
               '2018-08-23', '2018-08-24'],
              dtype='datetime64[ns]', length=9507, freq=None)

In [105]:
aapl_kg1 = aapl.loc[:pd.Timestamp(year=2014, month=12, day=2)].copy()

In [106]:
aapl_kg1

,ticker,open,close,adj_close,low,high,volume
1980-12-12,AAPL,0.513393,0.513393,0.023186,0.513393,0.515625,117258400
1980-12-15,AAPL,0.488839,0.486607,0.021977,0.486607,0.488839,43971200
1980-12-16,AAPL,0.453125,0.450893,0.020364,0.450893,0.453125,26432000
1980-12-17,AAPL,0.462054,0.462054,0.020868,0.462054,0.464286,21610400
1980-12-18,AAPL,0.475446,0.475446,0.021473,0.475446,0.477679,18362400
...,...,...,...,...,...,...,...
2014-11-25,AAPL,119.070000,117.599998,110.059097,117.449997,119.750000,68840400
2014-11-26,AAPL,117.940002,119.000000,111.369316,117.830002,119.099998,40768300
2014-11-28,AAPL,119.269997,118.930000,111.303802,118.050003,119.400002,24814400
2014-12-01,AAPL,118.809998,115.070000,107.691330,111.269997,119.250000,83814000
2014-12-02,AAPL,113.500000,114.629997,107.279541,112.750000,115.750000,59348900

In [133]:
df2 = pd.read_csv('/Users/robin/Documents/nf-ds/capstone_nf/data/raw/historical_stock_prices.csv')
djia_symbols_list = ['AAPL', 'AXP', 'BA', 'CAT', 'CSCO', 'CVX', 'DIS', 'DOW', 'GS', 'HD', 'IBM', 'INTC', 'JNJ', 'JPM', 'KO', 'MCD', 'MMM', 'MRK', 'MSFT', 'NKE', 'PFE', 'PG', 'TRV', 'UNH', 'UTX', 'V', 'VZ', 'WBA', 'WMT', 'XOM']

In [183]:
len(df2['ticker'].unique())

5685

In [185]:
df2_descr = pd.read_csv('/Users/robin/Documents/nf-ds/capstone_nf/data/raw/historical_stocks.csv')

In [197]:
df2_descr['exchange']

array(['NASDAQ', 'NYSE'], dtype=object)

In [195]:
df2_descr['ticker'].shape

(6460,)

In [ ]:
## Dow Jones Industrial Average

In [134]:
for symb in djia_symbols_list:
    df = df2[df2['ticker'] == symb].copy()
    df.set_index('date', inplace=True,)
    df.index = [pd.Timestamp(x) for x in df.index]
    df_kg1 = df.loc[:pd.Timestamp(year=2014, month=12, day=2)].copy()
    data = np.array([(df_kg1.index[i].value / 10**9, df_kg1['open'][i], df_kg1['high'][i], df_kg1['low'][i], df_kg1['close'][i], df_kg1['volume'][i]) for i in range(len(df_kg1))],
                     dtype=[('Epoch', 'i8'), ('Open', 'f4'), ('High', 'f4'), ('Low', 'f4'), ('Close', 'f4'), ('Volume', 'i4')])
    cli.write(data, symb+'/1D/OHLCV')

In [209]:
## S&P 500

import json
import urllib.request
import urllib

In [245]:
sp500_symbols_list = pd.read_csv('https://datahub.io/core/s-and-p-500-companies/r/constituents.csv')

In [248]:
sp500_symbols_list['Symbol'].nunique()

505

In [226]:
sp500_symbols_list_2 = [x for x in sp500_symbols_list['Symbol'].to_list() if x in df2_descr['ticker'].to_list()]

In [244]:
[x for x in sp500_symbols_list['Symbol'].to_list() if x not in sp500_symbols_list_2]

['CSRA']

In [273]:
cli = pymkts.Client('http://atomm.de:5993/rpc')
for symb in sp500_symbols_list['Symbol'].to_list():
    df = df2[df2['ticker'] == symb].copy()
    df.set_index('date', inplace=True,)
    df.index = [pd.Timestamp(x) for x in df.index]
    df_kg1 = df.copy()
    data = np.array([(df_kg1.index[i].value / 10**9, df_kg1['open'][i], df_kg1['high'][i], df_kg1['low'][i], df_kg1['close'][i], df_kg1['volume'][i]) for i in range(len(df_kg1))],
                     dtype=[('Epoch', 'i8'), ('Open', 'f4'), ('High', 'f4'), ('Low', 'f4'), ('Close', 'f4'), ('Volume', 'i4')])
    cli.write(data, symb+'/1D/OHLCV')

In [232]:
cli = pymkts.Client('http://atomm.de:5993/rpc')

In [274]:
ms_symbols_list = cli.list_symbols()

In [272]:
missing_symbols = [x for x in sp500_symbols_list if x not in ms_symbols_list]
missing_symbols

['Symbol', 'Name', 'Sector']

In [277]:
'TEST' in ms_symbols_list

True

In [249]:
axp = dm.ReturnData('AXP', limit=None)